# Generated by Django 4.2.16 on 2024-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
